<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ManageContact.aspx.cs" Inherits="Admin_ManageContact" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
     <style>
        .container{
            max-width: 1200px;
            width: 90%;
            margin: auto;
        }

        .navbar{
            box-shadow: 0px 5px 10px 0px #aaa;
            position: fixed;
            width: 100%;
            background: #fff7f8;
            color: #000;
            opacity: 0.85;
            z-index: 100;
        }

        .navbar-container{
            display: flex;
            justify-content: space-between;
            height: 64px;
            align-items: center;
        }

        .menu-items{
            order: 2;
            display: flex;
        }
     .logo{
    order: 1;
    font-size: 2.3rem;
    color: #ff3e55;
    font-family:Tahoma;
        }
        .menu-items li{
            list-style: none;
            margin-left: 1.5rem;
            font-size: 1.3rem;
        }

        .navbar a{
            color: #444;
            text-decoration: none;
            font-weight: 500;
            transition: color 0.3s ease-in-out;
        }

       .navbar a:hover{
    color: #e4001e;
}
        .main
        {
            position:absolute;
            top:13%;
            left:20%;
            width:1000px;
            }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
     <nav class="navbar">
     <div class="navbar-container container">
     <h1 class="logo">Ganesh Hall </h1>
     <ul class="menu-items">
                <li><a href="AdminPanleHome.aspx">Home</a></li>
        </ul>
     </div>
     </nav>
    </div>
    <div class=main>
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
            AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
            CellPadding="4" DataSourceID="SqlDataSource1" Width="80%" 
            DataKeyNames="id" onselectedindexchanged="GridView1_SelectedIndexChanged" 
            ForeColor="#333333" GridLines="None">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="name" HeaderText="Name" SortExpression="name">
                <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                </asp:BoundField>
                <asp:BoundField DataField="con" HeaderText="Conntact No" SortExpression="con">
                <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                </asp:BoundField>
                <asp:BoundField DataField="msg" HeaderText="Message" SortExpression="msg">
                <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                </asp:BoundField>
            </Columns>
            <EditRowStyle BackColor="#2461BF" />
            <FooterStyle BackColor="#507CD1" ForeColor="White" Font-Bold="True" />
            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <PagerStyle ForeColor="White" HorizontalAlign="Center" BackColor="#2461BF" />
            <RowStyle BackColor="#EFF3FB" />
            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F5F7FB" />
            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
            <SortedDescendingCellStyle BackColor="#E9EBEF" />
            <SortedDescendingHeaderStyle BackColor="#4870BE" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
            SelectCommand="SELECT [id], [name], [con], [msg] FROM [cust]" DeleteCommand="DELETE from [cust] where [id]=@id"></asp:SqlDataSource>
    </div>
    </form>
</body>
</html>
